(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-modes nil)
 '(blacken-executable "/opt/homebrew/bin/black")
 '(blacken-line-length 100)
 '(blink-cursor-mode nil)
 '(bm-buffer-persistence t)
 '(c-basic-offset 'set-from-style)
 '(c-default-style '((java-mode . "java") (awk-mode . "awk") (other . "k&r")))
 '(c-offsets-alist '((innamespace . +)))
 '(clang-format+-always-enable t)
 '(clang-format-executable "/usr/local/bin/clang-format")
 '(cmake-format-command "/opt/homebrew/bin/cmake-format")
 '(column-number-mode t)
 '(compilation-scroll-output 'first-error)
 '(compilation-skip-threshold 2)
 '(cursor-in-non-selected-windows nil)
 '(display-buffer-reuse-frames t)
 '(gofmt-command "/opt/homebrew/bin/gofmt")
 '(ido-cannot-complete-command 'ido-next-match)
 '(ido-default-buffer-method 'selected-window)
 '(ido-enable-flex-matching t)
 '(ido-max-window-height 1)
 '(ido-mode 'buffer nil (ido))
 '(initial-buffer-choice t)
 '(js-indent-level 2)
 '(kde-use-pc-select nil)
 '(kill-do-not-save-duplicates t)
 '(latex-indent-within-escaped-parens t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount '(1 ((shift) . 5) ((control))))
 '(mouse-yank-at-point t)
 '(package-selected-packages
   '(rust-mode jenkinsfile-mode bm terraform-mode cuda-mode yaml-mode go-mode ## cython-mode dockerfile-mode use-package clang-format+ cmake-mode typescript-mode google-c-style markdown-mode clang-format))
 '(pc-select-selection-keys-only t)
 '(pc-selection-mode nil)
 '(python-indent-def-block-scale 1)
 '(quack-default-program "mit-scheme")
 '(scroll-bar-mode 'right)
 '(sh-indent-after-continuation 'always)
 '(shift-select-mode nil)
 '(show-paren-delay 0)
 '(show-paren-mode t)
 '(special-display-buffer-names '("*compilation*"))
 '(special-display-function 'prefer-other-frame)
 '(tab-width 4)
 '(tool-bar-mode nil)
 '(typescript-mode-hook '(clang-format-on-save))
 '(x-stretch-cursor nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "ivory2" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 125 :width normal :foundry "unknown" :family "Menlo"))))
 '(bm-face ((((class color) (background light)) (:background "bisque"))))
 '(bm-fringe-persistent-face ((t (:background "bisque"))))
 '(bm-persistent-face ((t (:background "bisque"))))
 '(cursor ((t (:background "red3"))))
 '(paren-face-match ((t (:background "darkseagreen2"))))
 '(sh-heredoc ((t (:foreground "DodgerBlue1"))))
 '(show-paren-match ((t (:background "darkseagreen2")))))
